// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./../src/components/error/404.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    'IEp:circleCloseFilled': typeof import('~icons/ep/circle-close-filled')['default']
    'IEp:loading': typeof import('~icons/ep/loading')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    Tabs: typeof import('./../src/components/Tabs.vue')['default']
  }
}

export { }
